// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8SrEf3Nwqd4YSI0wwjRWw8501pFlYoA',
    appId: '1:195693504792:web:3fb0ce401e6ad0b4d9966d',
    messagingSenderId: '195693504792',
    projectId: 'sekolah-f6584',
    authDomain: 'sekolah-f6584.firebaseapp.com',
    storageBucket: 'sekolah-f6584.firebasestorage.app',
    measurementId: 'G-D9BG2WECVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWA78XpzpfPXnud27b5popzlq2wasvkk',
    appId: '1:195693504792:android:23339c1ed8c84cfad9966d',
    messagingSenderId: '195693504792',
    projectId: 'sekolah-f6584',
    storageBucket: 'sekolah-f6584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0oSnv8Rau0kCLiaG9ygpvwU1UkXXqrSE',
    appId: '1:195693504792:ios:fc28d484d1ae863ad9966d',
    messagingSenderId: '195693504792',
    projectId: 'sekolah-f6584',
    storageBucket: 'sekolah-f6584.firebasestorage.app',
    iosBundleId: 'com.sekolah.sekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0oSnv8Rau0kCLiaG9ygpvwU1UkXXqrSE',
    appId: '1:195693504792:ios:fc28d484d1ae863ad9966d',
    messagingSenderId: '195693504792',
    projectId: 'sekolah-f6584',
    storageBucket: 'sekolah-f6584.firebasestorage.app',
    iosBundleId: 'com.sekolah.sekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr8SrEf3Nwqd4YSI0wwjRWw8501pFlYoA',
    appId: '1:195693504792:web:5e091fa3e7d14654d9966d',
    messagingSenderId: '195693504792',
    projectId: 'sekolah-f6584',
    authDomain: 'sekolah-f6584.firebaseapp.com',
    storageBucket: 'sekolah-f6584.firebasestorage.app',
    measurementId: 'G-HTRD6MZ2PV',
  );
}
